[workspace]
resolver = "2"
members = [
    "indexmod",
    "indexmod-web",
]

[profile.release]
lto = true
# debug = true
codegen-units = 1

[profile.release-with-debug]
inherits="release"
# debug = true
