name: "CI"
on:
  push:
    branches:
      - dev
      - master

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  build:
    name: "Run TODO to Issue"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4
        with:
          AUTO_ASSIGN: true

